### ISSUE TITLE
Transforming the data into a suitable format

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#1]
**Dependent on**

- https://github.com/LisaRebecca/data-engineering-showcase/issues/6

**Tasks**

- [x] Pull data sets from the internet
- [x] Transform the data
- [x] Fix errors in the data

**Deliverables**

- [x] One script handling all three tasks, placed in /project directory
