### ISSUE TITLE
Create visualizations

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#10]
**Tasks**

- [x] Plan the final presentation
- [x] Identify which insights shall be presented
- [x] Create visualizations which showcase the insights

**Deliverables**

- [x] Rendered pictures for the final presentation
