### ISSUE TITLE
Making the repository presentable

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#11]
**Tasks**

- [x] Choose an appropriate open-source license (like [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/))
- [x] add it to your repository (see [GitHub documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository))
- [x] Polish the README 
- [x] Polish documentation, e.g., add the title of your project, a short description, embed your presentation slides/video (see below), and link the final report
- [ ] Optionally, proudly share your repository with the world with the hashtag #JValueMADE

**Deliverables**

- [x] License in GitHub Repository
- [x] README
