### ISSUE TITLE
Create final presentation

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#12]
**Tasks**

- [ ] Create presentation slides
- [ ] Create presentation video

**Deliverables**

- [ ] Slides in /project/slides.pdf
- [ ] Video in /project/slides-video.<video file format>
