### ISSUE TITLE
Formulate a research question

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#13]
**Tasks**

- [ ] Formulate a research question in one sentence
- [ ] State the motivation
- [ ] Add both to the project plan

**Deliverables**

- [ ] Project plan containing research question and motivation

**Comment by LisaRebecca** [comment]
**Deliverables**

- [research question](https://github.com/LisaRebecca/data-engineering-showcase/blob/main/project/project-plan.md#main-question) 
- [motivation](https://github.com/LisaRebecca/data-engineering-showcase/blob/main/project/project-plan.md#description)
