### ISSUE TITLE
Identify data sources

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#14]
**Tasks**

- [x] Identify at least two data sources
- [x] Access the data, check availability

**Deliverables**

- [x] List of data sources in project plan

**Comment by LisaRebecca** [comment]
**Deliverables**
[List of data sources in project plan](https://github.com/LisaRebecca/data-engineering-showcase/blob/main/project/project-plan.md#datasources)
