### ISSUE TITLE
Making the datasources available to the project

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#2]
**Dependent on**

- https://github.com/LisaRebecca/data-engineering-showcase/issues/6
- https://github.com/LisaRebecca/data-engineering-showcase/issues/1

**Tasks**

- [x] Extend the data transformation script with functionality to store the data
- [x] Provide a short example on how to retrieve the data from the stored format

**Deliverables**

- [x] Extended script in /project directory
- [x] Example script for loading data into memory and accessing it
