### ISSUE TITLE
Assess the Data Sources

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#3]
**Dependent on**

- https://github.com/LisaRebecca/data-engineering-showcase/issues/13
- https://github.com/LisaRebecca/data-engineering-showcase/issues/14

**Tasks**
- [x] Verify the license
- [x] Evaluate the source of the data
- [x] Preview the Data

**Deliverables**

- [x] short description of each data source including licensing and data publisher
