### ISSUE TITLE
Perform exploratory data analysis and initial visualization

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#4]
**Tasks**

- [ ] Get an overview on the contents of all datasets
- [ ] Create initial visualizations

**Deliverables**

- [ ] Jupyter notebook documenting the data exploration
