### ISSUE TITLE
Identifying a suitable data storage format for the goal

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#6]
**Tasks**

- [x] Identify common methods of data storage
- [x] Evaluate methods with respect to given project parameters
- [x] Select the most appropriate method

**Deliverables**

- [x] File with comparison and final decision
