### ISSUE TITLE
Evaluate the data sources with respect to their ability to answer the initial research question

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#7]
**Dependent on**

- https://github.com/LisaRebecca/data-engineering-showcase/issues/4

**Tasks**
- [ ] Identify parts of the data relevant for the research question
- [ ] Perform small feasibility tests on subsets of the data
- [ ] Which questions can be answered with the data?

**Deliverables**

- [ ] Short report about the ability of the data to answer the research question
