### ISSUE TITLE
Select appropriate algorithms and approaches to analysing the data

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#8]
**Dependent on**

- https://github.com/LisaRebecca/data-engineering-showcase/issues/4
- https://github.com/LisaRebecca/data-engineering-showcase/issues/7

**Tasks**

- [x] Create a plan on how to answer the research question using algorithms
- [x] Compare different approaches (esp. w.r.t. runtime/hardware feasibility)

**Deliverables**

- [x] Short description of the action plan of analysing the data
