### ISSUE TITLE
Evaluate the analysis results

### ISSUE THREAD

**Issue by LisaRebecca** [LisaRebecca/data-engineering-showcase#9]
**Tasks**

- [x] Evaluate whether the research question is answered
- [x] Answer the research question using the data

**Deliverables**

- [x] Updated project report
